### ISSUE TITLE
pull access denied for fpc/fpc-simple-asset-go-hw, failed to parse connections: EOF

### ISSUE THREAD

**Issue by yangjucai** [hyperledger/fabric-private-chaincode#755] opened 2024-02-23 12:28 UTC
**Describe the bug**

1. pull access denied for fpc/fpc-simple-asset-go-hw
Create a Makefile (i.e., touch $FPC_PATH/samples/chaincode/simple-asset-go/Makefile) with the following content:
TOP = ../../..
include $(TOP)/ecc_go/build.mk

CC_NAME ?= simple-asset-go

This Makefile would trigger an error in the following step:

>make ercc-ecc-start
Error response from daemon: pull access denied for fpc/fpc-simple-asset-go-hw, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

2. Test network successfully started, but invoke with error "failed to parse connections: EOF"
![image](https://github.com/hyperledger/fabric-private-chaincode/assets/75882421/1a992c82-8330-4662-9f5e-690a4df029f3)
![image](https://github.com/hyperledger/fabric-private-chaincode/assets/75882421/0927a515-45cf-4835-ba1a-a28d66990770)

*To Reproduce*

1.
Follow the FPC Go Simple Asset Tutorial.
See the error in the step 'make ercc-ecc-start'
Expected behavior

Change "CC_NAME ?= simple-asset-go" to "CC_NAME ?= fpc-simple-asset-go" in the Makefile

2.
Execute update-connection.sh using yq v4.x,  this bash file will produce an empty file.

I roll back to the previous version that supports yq v3.x.

**Environment (please complete the following information):**

Ubuntu 20.04
FPC Version ([e0eb483](https://github.com/hyperledger/fabric-private-chaincode/commit/e0eb48347651ca570d82091d3fbf90d59a5a4ffe))
yq v4.41.1

**Comment by mbrandenburger** [comment] 2024-03-19 14:32
@yangjucai thanks for reporting this. Let me try to reproduce the error.

**Comment by mbrandenburger** [comment] 2024-04-11 14:36
Hi @yangjucai for some reason I cannot reproduce the issue regarding the error you describing here: "[pull access denied for fpc/fpc-simple-asset-go-hw, failed to parse connections: EOF](https://github.com/hyperledger/fabric-private-chaincode/issues/755#top)"

In particular, I am wondering where you observe the pull access denied error? In the screenshot I can see that you run a container from that image.

**Comment by mbrandenburger** [comment] 2024-04-29 17:01
Closing this one for now. Feel free to reopen if the error still occurs.

**Closed by mbrandenburger** 2024-04-29 17:01 UTC
Labels: bug

**Comment by zking666** [comment] 2024-05-20 09:12
I encountered almost the same issue. Following your two solutions mentioned earlier, I managed to solve part of the problem and no longer face the access denied issue. However, I can't run the update script properly with yq version 3.The main reason is that version 3 does not support the eval-all parameter. The current situation is as shown in the picture.
![微信截图_20240520170858](https://github.com/hyperledger/fabric-private-chaincode/assets/73631276/54c289ad-c81a-444f-833d-59b8a3d2c275)
![微信截图_20240520171018](https://github.com/hyperledger/fabric-private-chaincode/assets/73631276/a31bb6a4-e3a1-477f-b170-35f36dd1a87c)
![微信图片_20231010172937](https://github.com/hyperledger/fabric-private-chaincode/assets/73631276/394e8fe9-5f07-45be-8679-e1702098e737)
Related file is empty.
![2](https://github.com/hyperledger/fabric-private-chaincode/assets/73631276/1504f059-497e-4dea-b91d-fa19fe4c04ba)

**Comment by zking666** [comment] 2024-05-20 09:13
I encountered almost the same issue. Following your two solutions mentioned earlier, I managed to solve part of the problem and no longer face the access denied issue. However, I can't run the update script properly with yq version 3.The main reason is that version 3 does not support the eval-all parameter. The current situation is as shown in the picture.
![2](https://github.com/hyperledger/fabric-private-chaincode/assets/73631276/a0dc5141-35fc-4ef1-a7c8-5fab2aaa30b9)
![1716196181938](https://github.com/hyperledger/fabric-private-chaincode/assets/73631276/7b3b3732-c101-4e33-b865-436056412c93)
![微信截图_20240520170858](https://github.com/hyperledger/fabric-private-chaincode/assets/73631276/fe713580-8728-4469-95c0-dfbf863389dd)
![微信截图_20240520171018](https://github.com/hyperledger/fabric-private-chaincode/assets/73631276/054928d5-8b76-4c93-8b13-c557f614e58c)

**Comment by mbrandenburger** [comment] 2024-05-21 11:59
@zking666 Ouch! yq v3 and v4 are unfortunately not compatible. However, the latest FPC version on main uses yq v4 in the test-network sample.  
See https://github.com/hyperledger/fabric-private-chaincode/commit/78c6117a7a5949b366fa88c8c1be30f13d6145ce 

The second screenshot you are sharing, it seems you have yq v4 and updating.
